# Generated by Django 5.0.4 on 2026-03-17 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong Answer'), ('RUNTIME_ERROR', 'Runtime Error'), ('TIME_LIMIT', 'Time Limit Exceeded'), ('MEMORY_LIMIT', 'Memory Limit Exceeded')], max_length=20)),
                ('actual_output', models.TextField(blank=True)),
                ('expected_output', models.TextField(blank=True)),
                ('error_output', models.TextField(blank=True)),
                ('time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_kb', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'submission_results',
                'ordering': ['test_case__order_index'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('python', 'Python 3'), ('cpp', 'C++ 17'), ('java', 'Java 17'), ('javascript', 'JavaScript (Node)')], max_length=20)),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong Answer'), ('RUNTIME_ERROR', 'Runtime Error'), ('TIME_LIMIT', 'Time Limit Exceeded'), ('MEMORY_LIMIT', 'Memory Limit Exceeded'), ('COMPILE_ERROR', 'Compile Error'), ('INTERNAL_ERROR', 'Internal Error')], db_index=True, default='QUEUED', max_length=20)),
                ('runtime_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('judge_started_at', models.DateTimeField(blank=True, null=True)),
                ('judge_finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='contests.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
