# Generated by Django 5.0.4 on 2026-03-17 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionresult',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='submissions.submission'),
        ),
        migrations.AddField(
            model_name='submissionresult',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.testcase'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['user', 'problem', '-created_at'], name='submissions_user_id_16091b_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', '-created_at'], name='submissions_status_51c352_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['problem', 'status'], name='submissions_problem_b4f4fb_idx'),
        ),
    ]
