# Generated by Django 5.0.4 on 2026-04-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_sample_run',
            field=models.BooleanField(default=False),
        ),
    ]
