# Generated by Django 5.0.4 on 2026-03-21 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('position', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ad_placements',
            },
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('html_snippet', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('link_url', models.URLField()),
                ('plan_target', models.CharField(choices=[('FREE', 'FREE'), ('PRO', 'PRO')], default='FREE', max_length=10)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='content.adplacement')),
            ],
            options={
                'db_table': 'ad_creatives',
                'ordering': ['-priority'],
            },
        ),
    ]
