# Generated by Django 5.0.4 on 2026-04-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='best_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
