# Generated by Django 5.0.4 on 2026-03-17 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discussions', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discussioncomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_threads', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='discussioncomment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='discussions.discussionthread'),
        ),
        migrations.AddIndex(
            model_name='discussionthread',
            index=models.Index(fields=['problem', '-created_at'], name='discussion__problem_d32a65_idx'),
        ),
        migrations.AddIndex(
            model_name='discussionthread',
            index=models.Index(fields=['author', '-created_at'], name='discussion__author__dbc375_idx'),
        ),
        migrations.AddIndex(
            model_name='discussioncomment',
            index=models.Index(fields=['thread', '-created_at'], name='discussion__thread__ae6b17_idx'),
        ),
        migrations.AddIndex(
            model_name='discussioncomment',
            index=models.Index(fields=['author', '-created_at'], name='discussion__author__525185_idx'),
        ),
    ]
