# Generated by Django 5.0.4 on 2026-03-21 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussioncomment',
            options={'ordering': ['-is_accepted_answer', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='discussioncomment',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='discussioncomment',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussioncomment',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussioncomment',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussioncomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='discussions.discussioncomment'),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CommentUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='discussions.discussioncomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discussion_comment_upvotes',
                'indexes': [models.Index(fields=['comment', 'user'], name='discussion__comment_ecacd9_idx'), models.Index(fields=['user', '-created_at'], name='discussion__user_id_a1b217_idx')],
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ThreadUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='discussions.discussionthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discussion_thread_upvotes',
                'indexes': [models.Index(fields=['thread', 'user'], name='discussion__thread__93999e_idx'), models.Index(fields=['user', '-created_at'], name='discussion__user_id_aba904_idx')],
                'unique_together': {('thread', 'user')},
            },
        ),
    ]
