# Generated by Django 5.0.4 on 2026-03-17 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contestparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_problems', to='contests.contest'),
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem'),
        ),
        migrations.AlterUniqueTogether(
            name='contestparticipant',
            unique_together={('contest', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='contestproblem',
            unique_together={('contest', 'problem')},
        ),
    ]
