# Generated by Django 5.0.4 on 2026-04-12 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestSubmissionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solved', models.BooleanField(default=False)),
                ('wrong_attempts', models.IntegerField(default=0)),
                ('solve_time_minutes', models.IntegerField(blank=True, null=True)),
                ('score_awarded', models.IntegerField(default=0)),
                ('first_solved_at', models.DateTimeField(blank=True, null=True)),
                ('contest_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='contests.contestproblem')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_stats', to='contests.contestparticipant')),
            ],
            options={
                'db_table': 'contest_submission_stats',
                'unique_together': {('participant', 'contest_problem')},
            },
        ),
    ]
