# Generated by Django 5.0.4 on 2026-03-17 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ARRAY', 'Array'), ('STRING', 'String'), ('LINKED_LIST', 'Linked List'), ('TREE', 'Tree'), ('GRAPH', 'Graph'), ('DP', 'Dynamic Programming'), ('BACKTRACKING', 'Backtracking'), ('BINARY_SEARCH', 'Binary Search'), ('HEAP', 'Heap / Priority Queue'), ('STACK', 'Stack'), ('QUEUE', 'Queue'), ('HASH_MAP', 'Hash Map / Set'), ('TWO_POINTERS', 'Two Pointers'), ('SLIDING_WINDOW', 'Sliding Window'), ('BIT_MANIPULATION', 'Bit Manipulation'), ('MATH', 'Math & Geometry'), ('GREEDY', 'Greedy'), ('INTERVALS', 'Intervals'), ('OTHER', 'Other')], max_length=30, unique=True)),
                ('display_name', models.CharField(max_length=60)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon class', max_length=50)),
            ],
            options={
                'db_table': 'sections',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('tag_type', models.CharField(choices=[('TOPIC', 'Topic'), ('COMPANY', 'Company')], db_index=True, max_length=10)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('number', models.PositiveIntegerField(blank=True, help_text='LeetCode-style problem number', null=True)),
                ('statement_md', models.TextField(help_text='Problem statement in Markdown')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], db_index=True, max_length=10)),
                ('visibility', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro Only')], default='FREE', max_length=10)),
                ('time_complexity_best', models.CharField(blank=True, help_text='e.g. O(n)', max_length=40)),
                ('time_complexity_average', models.CharField(blank=True, help_text='e.g. O(n log n)', max_length=40)),
                ('time_complexity_worst', models.CharField(blank=True, help_text='e.g. O(n²)', max_length=40)),
                ('space_complexity', models.CharField(blank=True, help_text='e.g. O(1)', max_length=40)),
                ('complexity_notes_md', models.TextField(blank=True)),
                ('hints_md', models.TextField(blank=True, help_text='Hints separated by --- on its own line')),
                ('total_submissions', models.PositiveIntegerField(default=0)),
                ('accepted_submissions', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems', to='problems.section')),
            ],
            options={
                'db_table': 'problems',
                'ordering': ['number', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'Approach 1: HashMap'", max_length=200)),
                ('approach_summary_md', models.TextField(help_text='Step-by-step explanation in Markdown')),
                ('code_python', models.TextField(blank=True)),
                ('code_cpp', models.TextField(blank=True)),
                ('code_java', models.TextField(blank=True)),
                ('code_javascript', models.TextField(blank=True)),
                ('time_complexity', models.CharField(blank=True, max_length=40)),
                ('space_complexity', models.CharField(blank=True, max_length=40)),
                ('complexity_explanation_md', models.TextField(blank=True)),
                ('is_official', models.BooleanField(default=True)),
                ('visibility', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro Only')], default='FREE', max_length=10)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='problems.problem')),
            ],
            options={
                'db_table': 'solutions',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.tag')),
            ],
            options={
                'db_table': 'problem_tags',
                'unique_together': {('problem', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, through='problems.ProblemTag', to='problems.tag'),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('explanation', models.TextField(blank=True, help_text='Explanation shown for sample test cases')),
                ('is_sample', models.BooleanField(default=False, help_text='Shown to the user on problem page')),
                ('is_hidden', models.BooleanField(default=True, help_text='Used by judge but not revealed')),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem')),
            ],
            options={
                'db_table': 'test_cases',
                'ordering': ['order_index'],
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['difficulty', 'is_published'], name='problems_difficu_bca2a0_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['section', 'is_published'], name='problems_section_f8daea_idx'),
        ),
    ]
