# Generated by Django 5.0.4 on 2026-03-17 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlog',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['admin', '-created_at'], name='admin_logs_admin_i_1c2db0_idx'),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['action', '-created_at'], name='admin_logs_action_22c8d4_idx'),
        ),
    ]
